### ISSUE TITLE
NuScenesSSL dataset preparation

### ISSUE THREAD

**Issue by ChenGY-THU** [Tsinghua-MARS-Lab/GeoMAE#3]
Thanks for your excellent work!
However, an error occurs when I run the instructions for preparing the NuScenesSSL dataset. Upon investigation, I found that this might be due to the 'pipeline' parameter being passed as 'None' during the initialization of NuScenesSSL. How can I resolve this issue?

Traceback (most recent call last):
  File "tools/create_data.py", line 306, in <module>
    nuscenes_data_prep(
  File "tools/create_data.py", line 81, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, info_prefix,
  File "/home/ps/project/GeoMAE/tools/data_converter/create_gt_database.py", line 238, in create_groundtruth_database
    example = dataset.pipeline(input_dict)
  File "/home/ps/anaconda3/envs/GeoMAE/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError

**Comment by saimunur** [comment]
@ChenGY-THU did you manage to solve the issue?
